# Raspberry Pi 4/5 及通用 aarch64 Linux 交叉编译。
#   cmake -S . -B build-aarch64 -DCMAKE_TOOLCHAIN_FILE=cmake/aarch64-linux-gnu.cmake
# Pi 5 再加 -DEDGEXPU_ARM_DOTPROD=ON

set(CMAKE_SYSTEM_NAME Linux)
set(CMAKE_SYSTEM_PROCESSOR aarch64)

set(EDGEXPU_AARCH64_TRIPLE "aarch64-linux-gnu" CACHE STRING "GNU aarch64 triple")

set(CMAKE_C_COMPILER "${EDGEXPU_AARCH64_TRIPLE}-gcc")
set(CMAKE_CXX_COMPILER "${EDGEXPU_AARCH64_TRIPLE}-g++")

set(CMAKE_FIND_ROOT_PATH "/usr/${EDGEXPU_AARCH64_TRIPLE}")
set(CMAKE_FIND_ROOT_PATH_MODE_PROGRAM NEVER)
set(CMAKE_FIND_ROOT_PATH_MODE_LIBRARY ONLY)
set(CMAKE_FIND_ROOT_PATH_MODE_INCLUDE ONLY)
set(CMAKE_FIND_ROOT_PATH_MODE_PACKAGE ONLY)
